### ISSUE TITLE
出现了一个问题,进度条不走了!

### ISSUE THREAD

**Issue by yangpf5271** [nilaoda/The-New-M3U8-Downloader#11]
[f4v @ 05edf8c0] Non-monotonous DTS in output stream 0:0; previous: 23783220, current: -1710; changing to 23783221. This may result in incorrect timestamps in the output file.

**Comment by nilaoda** [comment]
本工具已停止更新.
使用这个试试：https://github.com/nilaoda/m3u8_dl-js_GUI
