### ISSUE TITLE
请问有没有命令行的ui？

### ISSUE THREAD

**Issue by Michael-YS** [nilaoda/The-New-M3U8-Downloader#16]
请问有没有命令行的interface？
想用python做批量处理，如果每次手动复制就太麻烦了。

谢谢

**Comment by z2690108** [comment]
ffmpeg

**Comment by nilaoda** [comment]
https://github.com/nilaoda/N_m3u8DL-CLI

**Comment by Michael-YS** [comment]
> 
> 
> https://github.com/nilaoda/N_m3u8DL-CLI

谢谢
