### ISSUE TITLE
返回 HTTP error 403 Forbidden

### ISSUE THREAD

**Issue by ct8** [nilaoda/The-New-M3U8-Downloader#2]
你好，在下载有些akamaihd.net视频的时候，会返回 HTTP error 403 Forbidden 。估计是akamai加了验证，要浏览器才可以打开。可否加上一些user_agent或cookie什么的，将ffmpeg伪装成浏览器？

**Comment by nilaoda** [comment]
ffmpeg提供了 `-user-agent` ，但是本软件已不再更新……
