### ISSUE TITLE
Can we make an English version for this repo?

### ISSUE THREAD

**Issue by Shhzdmrz** [nilaoda/The-New-M3U8-Downloader#6]

**Comment by siddhantrimal** [comment]
Second this!  @nilaoda could you write all the words in the next comment and give their closest meaning (it's okay even if it's in Japanese). I'll try to translate somehow. Thanks!

以下のコメントでは、メニューとその最も近い意味から日本語の単語を書いてください。 それは私が英語に翻訳するのに役立ちます。 ご検討をお願いいたします。

**Comment by nilaoda** [comment]
Be my guest. @Shhzdmrz @siddhantrimal
